title: Programa de Onboarding
tagline: A Jekyll template for course websites
description: Programa de Onboarding para nuevos colaboradores en Ethereum Costa Rica
author: Onboarding ETH CR
baseurl: /Prueba-de-Programa
url: https://onboardingethcr.github.io
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

theme: just-the-class
repository: OnboardingETHCR/Prueba-de-Programa
permalink: pretty
footer_content:

collections:
  staffers:
  modules:
  schedules:
  announcements:
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true

