title: Programa de Onboarding
description: Curso de introducción a Blockchain y Web3
author: Onboarding ETH CR

url: "https://onboardingethcr.github.io"
baseurl: "/Prueba-de-Programa"

remote_theme: kevinlin1/just-the-class

repository: OnboardingETHCR/Prueba-de-Programa
permalink: pretty

footer_content: "© 2025 Ethereum Costa Rica"

collections:
  pages:
    output: true
    permalink: /:path/

defaults: []

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true
